---
- name: Complete Chapter 1 Lab
  hosts: localhost
  vars_files: sat_vars.yml
  vars:
    org_name: Finance
    org_desc: Finance Department
    org_locations:
      - San Francisco
      - Tokyo
  tasks:

### This task should create the lab Organization
    - name: Create Lab Organization
      redhat.satellite.organization:
        name: "{{ org_name }}"
        description: "{{ org_desc }}" 
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"

### This task should create the lab Location(s) 
    - name: Create Lab Locations
      redhat.satellite.location:
        name: "{{ item }}"
        organizations: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
      loop: "{{ org_locations }}"


### This has been done for you to obtain the manifest for next task
    - name: Download Manifest from Classroom
      get_url:
        url: http://materials/manifest_finance.zip
        dest: "/tmp/manifest_finance.zip"

### This task shoud upload the manifest and set the content URL
    - name: Upload Manifest
      redhat.satellite.subscription_manifest:
        organization: "{{ org_name }}"
        state: present
        server_url: "{{ sat_url }}"
        username: "{{ sat_un }}"
        password: "{{ sat_pw }}"
        validate_certs: "{{ cert_validate }}"
        manifest_path: "/tmp/manifest_finance.zip"
        repository_url: http://content.example.com/rhs6.6/x86_64/cdn
